#!/bin/sh
USER=ville
HOST=m73-1.mandariini.uk
DIR=/srv/nfs/nginx-ville/   # the directory where your website files should go

hugo && rsync -avz --delete public/ ${USER}@${HOST}:${DIR} # this will delete everything on the server that's not in the local public directory 

exit 0